/* eslint-disable */
import * as types from "./graphql";
import { TypedDocumentNode as DocumentNode } from "@graphql-typed-document-node/core";

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
  "query CollectionPage($slug: String!, $releaseLimit: Int!) {\n  collection(slug: $slug) {\n    slug\n    name\n    description\n    isFeatured\n    dailySummaryEnabled\n    members {\n      __typename\n      ... on CollectionMemberOrg {\n        slug\n        name\n        domain\n        avatarUrl\n        githubHandle\n        description\n      }\n      ... on CollectionMemberProduct {\n        slug\n        name\n        description\n        org {\n          slug\n          name\n          domain\n          avatarUrl\n          githubHandle\n        }\n      }\n    }\n    releases(limit: $releaseLimit) {\n      nextCursor\n      items {\n        id\n        title\n        version\n        type\n        url\n        publishedAt\n        summary\n        content\n        titleGenerated\n        titleShort\n        prerelease\n        media {\n          type\n          url\n          alt\n          r2Url\n        }\n        source {\n          slug\n          name\n          type\n        }\n        org {\n          slug\n          name\n        }\n        product {\n          slug\n          name\n        }\n        groupSlug\n        groupName\n        coverageCount\n        composition {\n          bugs\n          features\n          enhancements\n        }\n      }\n    }\n    dailySummaries {\n      date\n      title\n      summary\n      takeaways\n      releaseCount\n    }\n  }\n}": typeof types.CollectionPageDocument;
  "query HomepageAllOrgs($limit: Int!) {\n  orgs(includeEmpty: false, limit: $limit) {\n    items {\n      slug\n      name\n      domain\n      avatarUrl\n      sourceCount\n      releaseCount\n      recentReleaseCount\n      lastActivity\n      topProducts\n      sparkline\n    }\n  }\n}": typeof types.HomepageAllOrgsDocument;
  "query HomepageCollections($featured: Boolean) {\n  collections(featured: $featured) {\n    slug\n    name\n    description\n    memberCount\n    isFeatured\n    previewMembers {\n      __typename\n      ... on CollectionMemberOrg {\n        slug\n        name\n        avatarUrl\n        githubHandle\n      }\n      ... on CollectionMemberProduct {\n        slug\n        name\n        org {\n          slug\n          name\n          avatarUrl\n          githubHandle\n        }\n      }\n    }\n  }\n}": typeof types.HomepageCollectionsDocument;
  "query HomepageOrgsStats($featuredLimit: Int!) {\n  stats {\n    orgs\n    sources\n    releases\n  }\n  featuredOrgs: orgs(featured: true, limit: $featuredLimit) {\n    items {\n      slug\n      name\n      domain\n      avatarUrl\n      sourceCount\n      releaseCount\n      recentReleaseCount\n      lastActivity\n      topProducts\n      sparkline\n    }\n  }\n}": typeof types.HomepageOrgsStatsDocument;
  "query HomepageTicker($limit: Int!, $exclude: [SourceType!]!) {\n  latestReleases(limit: $limit, excludeSourceTypes: $exclude) {\n    items {\n      id\n      title\n      version\n      publishedAt\n      titleGenerated\n      titleShort\n      source {\n        org {\n          slug\n          name\n          avatarUrl\n        }\n        product {\n          slug\n          name\n        }\n        appStore {\n          platform\n          iconUrl\n        }\n        video {\n          provider\n        }\n      }\n    }\n  }\n}": typeof types.HomepageTickerDocument;
  "query OrgPage($idOrSlug: String!) {\n  org(idOrSlug: $idOrSlug) {\n    id\n    slug\n    name\n    domain\n    description\n    category\n    avatarUrl\n    isHidden\n    autoGenerateContent\n    overviewCadenceDays\n    featured\n    fetchPaused\n    discovery\n    status\n    locations\n    tags\n    aliases\n    notice\n    sourceCount\n    releaseCount\n    releasesLast30Days\n    avgReleasesPerWeek\n    lastFetchedAt\n    lastPolledAt\n    trackingSince\n    accounts {\n      platform\n      handle\n    }\n    products {\n      id\n      slug\n      name\n      url\n      description\n      kind\n      createdAt\n      sourceCount\n      releaseCount\n    }\n    collections {\n      slug\n      name\n      description\n      memberCount\n      isFeatured\n    }\n    sources {\n      id\n      slug\n      name\n      type\n      url\n      fetchPriority\n      lastFetchedAt\n      lastPolledAt\n      medianGapDays\n      discovery\n      createdAt\n      kind\n      isPrimary\n      isHidden\n      changeDetectedAt\n      consecutiveNoChange\n      consecutiveErrors\n      nextFetchAfter\n      lastRetieredAt\n      metadata\n      stars\n      starsFetchedAt\n      releaseCount\n      latestVersion\n      latestDate\n      latestAddedAt\n      appStore {\n        platform\n        iconUrl\n      }\n      video {\n        provider\n      }\n      product {\n        slug\n        name\n      }\n    }\n  }\n}": typeof types.OrgPageDocument;
  "query OrgReleases($orgIdOrSlug: String!, $limit: Int!) {\n  latestReleases(orgIdOrSlug: $orgIdOrSlug, limit: $limit) {\n    nextCursor\n    items {\n      id\n      title\n      version\n      type\n      url\n      publishedAt\n      fetchedAt\n      summary\n      titleGenerated\n      titleShort\n      content\n      prerelease\n      breaking\n      media {\n        type\n        url\n        alt\n        r2Url\n      }\n      source {\n        slug\n        name\n        type\n        appStore {\n          platform\n          iconUrl\n        }\n        video {\n          provider\n        }\n        product {\n          slug\n          name\n        }\n      }\n    }\n  }\n}": typeof types.OrgReleasesDocument;
  "query ProductPage($id: String!, $releaseLimit: Int!) {\n  product(id: $id) {\n    id\n    slug\n    name\n    url\n    description\n    category\n    tags\n    notice {\n      message\n      linkText\n      coordinate\n      href\n    }\n    sources {\n      id\n      slug\n      name\n      type\n      url\n      metadata\n      isHidden\n    }\n    collections {\n      slug\n      name\n      description\n      memberCount\n      isFeatured\n    }\n  }\n  latestReleases(productId: $id, limit: $releaseLimit) {\n    nextCursor\n    items {\n      id\n      title\n      version\n      type\n      url\n      publishedAt\n      fetchedAt\n      summary\n      titleGenerated\n      titleShort\n      content\n      prerelease\n      breaking\n      media {\n        type\n        url\n        alt\n        r2Url\n      }\n      source {\n        slug\n        name\n        type\n        appStore {\n          platform\n          iconUrl\n        }\n        video {\n          provider\n        }\n        product {\n          slug\n          name\n        }\n      }\n    }\n  }\n}": typeof types.ProductPageDocument;
  "query ReleaseDetail($idOrUrl: String!) {\n  release(idOrUrl: $idOrUrl) {\n    id\n    title\n    version\n    type\n    url\n    publishedAt\n    fetchedAt\n    summary\n    titleGenerated\n    titleShort\n    content\n    migrationNotes\n    composition {\n      bugs\n      features\n      enhancements\n    }\n    media {\n      type\n      url\n      alt\n      r2Url\n    }\n    source {\n      slug\n      name\n      type\n      isHidden\n      org {\n        slug\n        name\n        avatarUrl\n        isHidden\n        discovery\n      }\n      product {\n        slug\n        name\n      }\n      appStore {\n        platform\n        iconUrl\n      }\n      video {\n        provider\n      }\n    }\n  }\n}": typeof types.ReleaseDetailDocument;
  "query SourceDetail($id: String!, $releaseLimit: Int!) {\n  source(id: $id) {\n    id\n    slug\n    name\n    type\n    url\n    productId\n    isHidden\n    discovery\n    metadata\n    changelogUrl\n    hasChangelogFile\n    lastFetchedAt\n    lastPolledAt\n    trackingSince\n    latestVersion\n    latestDate\n    notice {\n      message\n      linkText\n      coordinate\n      href\n    }\n    summaries {\n      rolling {\n        year\n        month\n        windowDays\n        summary\n        releaseCount\n        generatedAt\n      }\n      monthly {\n        year\n        month\n        windowDays\n        summary\n        releaseCount\n        generatedAt\n      }\n    }\n    org {\n      id\n      slug\n      name\n    }\n    releases(limit: $releaseLimit) {\n      id\n      title\n      version\n      type\n      url\n      publishedAt\n      fetchedAt\n      titleGenerated\n      titleShort\n      content\n      summary\n      media {\n        type\n        url\n        alt\n        r2Url\n      }\n    }\n  }\n}": typeof types.SourceDetailDocument;
};
const documents: Documents = {
  "query CollectionPage($slug: String!, $releaseLimit: Int!) {\n  collection(slug: $slug) {\n    slug\n    name\n    description\n    isFeatured\n    dailySummaryEnabled\n    members {\n      __typename\n      ... on CollectionMemberOrg {\n        slug\n        name\n        domain\n        avatarUrl\n        githubHandle\n        description\n      }\n      ... on CollectionMemberProduct {\n        slug\n        name\n        description\n        org {\n          slug\n          name\n          domain\n          avatarUrl\n          githubHandle\n        }\n      }\n    }\n    releases(limit: $releaseLimit) {\n      nextCursor\n      items {\n        id\n        title\n        version\n        type\n        url\n        publishedAt\n        summary\n        content\n        titleGenerated\n        titleShort\n        prerelease\n        media {\n          type\n          url\n          alt\n          r2Url\n        }\n        source {\n          slug\n          name\n          type\n        }\n        org {\n          slug\n          name\n        }\n        product {\n          slug\n          name\n        }\n        groupSlug\n        groupName\n        coverageCount\n        composition {\n          bugs\n          features\n          enhancements\n        }\n      }\n    }\n    dailySummaries {\n      date\n      title\n      summary\n      takeaways\n      releaseCount\n    }\n  }\n}":
    types.CollectionPageDocument,
  "query HomepageAllOrgs($limit: Int!) {\n  orgs(includeEmpty: false, limit: $limit) {\n    items {\n      slug\n      name\n      domain\n      avatarUrl\n      sourceCount\n      releaseCount\n      recentReleaseCount\n      lastActivity\n      topProducts\n      sparkline\n    }\n  }\n}":
    types.HomepageAllOrgsDocument,
  "query HomepageCollections($featured: Boolean) {\n  collections(featured: $featured) {\n    slug\n    name\n    description\n    memberCount\n    isFeatured\n    previewMembers {\n      __typename\n      ... on CollectionMemberOrg {\n        slug\n        name\n        avatarUrl\n        githubHandle\n      }\n      ... on CollectionMemberProduct {\n        slug\n        name\n        org {\n          slug\n          name\n          avatarUrl\n          githubHandle\n        }\n      }\n    }\n  }\n}":
    types.HomepageCollectionsDocument,
  "query HomepageOrgsStats($featuredLimit: Int!) {\n  stats {\n    orgs\n    sources\n    releases\n  }\n  featuredOrgs: orgs(featured: true, limit: $featuredLimit) {\n    items {\n      slug\n      name\n      domain\n      avatarUrl\n      sourceCount\n      releaseCount\n      recentReleaseCount\n      lastActivity\n      topProducts\n      sparkline\n    }\n  }\n}":
    types.HomepageOrgsStatsDocument,
  "query HomepageTicker($limit: Int!, $exclude: [SourceType!]!) {\n  latestReleases(limit: $limit, excludeSourceTypes: $exclude) {\n    items {\n      id\n      title\n      version\n      publishedAt\n      titleGenerated\n      titleShort\n      source {\n        org {\n          slug\n          name\n          avatarUrl\n        }\n        product {\n          slug\n          name\n        }\n        appStore {\n          platform\n          iconUrl\n        }\n        video {\n          provider\n        }\n      }\n    }\n  }\n}":
    types.HomepageTickerDocument,
  "query OrgPage($idOrSlug: String!) {\n  org(idOrSlug: $idOrSlug) {\n    id\n    slug\n    name\n    domain\n    description\n    category\n    avatarUrl\n    isHidden\n    autoGenerateContent\n    overviewCadenceDays\n    featured\n    fetchPaused\n    discovery\n    status\n    locations\n    tags\n    aliases\n    notice\n    sourceCount\n    releaseCount\n    releasesLast30Days\n    avgReleasesPerWeek\n    lastFetchedAt\n    lastPolledAt\n    trackingSince\n    accounts {\n      platform\n      handle\n    }\n    products {\n      id\n      slug\n      name\n      url\n      description\n      kind\n      createdAt\n      sourceCount\n      releaseCount\n    }\n    collections {\n      slug\n      name\n      description\n      memberCount\n      isFeatured\n    }\n    sources {\n      id\n      slug\n      name\n      type\n      url\n      fetchPriority\n      lastFetchedAt\n      lastPolledAt\n      medianGapDays\n      discovery\n      createdAt\n      kind\n      isPrimary\n      isHidden\n      changeDetectedAt\n      consecutiveNoChange\n      consecutiveErrors\n      nextFetchAfter\n      lastRetieredAt\n      metadata\n      stars\n      starsFetchedAt\n      releaseCount\n      latestVersion\n      latestDate\n      latestAddedAt\n      appStore {\n        platform\n        iconUrl\n      }\n      video {\n        provider\n      }\n      product {\n        slug\n        name\n      }\n    }\n  }\n}":
    types.OrgPageDocument,
  "query OrgReleases($orgIdOrSlug: String!, $limit: Int!) {\n  latestReleases(orgIdOrSlug: $orgIdOrSlug, limit: $limit) {\n    nextCursor\n    items {\n      id\n      title\n      version\n      type\n      url\n      publishedAt\n      fetchedAt\n      summary\n      titleGenerated\n      titleShort\n      content\n      prerelease\n      breaking\n      media {\n        type\n        url\n        alt\n        r2Url\n      }\n      source {\n        slug\n        name\n        type\n        appStore {\n          platform\n          iconUrl\n        }\n        video {\n          provider\n        }\n        product {\n          slug\n          name\n        }\n      }\n    }\n  }\n}":
    types.OrgReleasesDocument,
  "query ProductPage($id: String!, $releaseLimit: Int!) {\n  product(id: $id) {\n    id\n    slug\n    name\n    url\n    description\n    category\n    tags\n    notice {\n      message\n      linkText\n      coordinate\n      href\n    }\n    sources {\n      id\n      slug\n      name\n      type\n      url\n      metadata\n      isHidden\n    }\n    collections {\n      slug\n      name\n      description\n      memberCount\n      isFeatured\n    }\n  }\n  latestReleases(productId: $id, limit: $releaseLimit) {\n    nextCursor\n    items {\n      id\n      title\n      version\n      type\n      url\n      publishedAt\n      fetchedAt\n      summary\n      titleGenerated\n      titleShort\n      content\n      prerelease\n      breaking\n      media {\n        type\n        url\n        alt\n        r2Url\n      }\n      source {\n        slug\n        name\n        type\n        appStore {\n          platform\n          iconUrl\n        }\n        video {\n          provider\n        }\n        product {\n          slug\n          name\n        }\n      }\n    }\n  }\n}":
    types.ProductPageDocument,
  "query ReleaseDetail($idOrUrl: String!) {\n  release(idOrUrl: $idOrUrl) {\n    id\n    title\n    version\n    type\n    url\n    publishedAt\n    fetchedAt\n    summary\n    titleGenerated\n    titleShort\n    content\n    migrationNotes\n    composition {\n      bugs\n      features\n      enhancements\n    }\n    media {\n      type\n      url\n      alt\n      r2Url\n    }\n    source {\n      slug\n      name\n      type\n      isHidden\n      org {\n        slug\n        name\n        avatarUrl\n        isHidden\n        discovery\n      }\n      product {\n        slug\n        name\n      }\n      appStore {\n        platform\n        iconUrl\n      }\n      video {\n        provider\n      }\n    }\n  }\n}":
    types.ReleaseDetailDocument,
  "query SourceDetail($id: String!, $releaseLimit: Int!) {\n  source(id: $id) {\n    id\n    slug\n    name\n    type\n    url\n    productId\n    isHidden\n    discovery\n    metadata\n    changelogUrl\n    hasChangelogFile\n    lastFetchedAt\n    lastPolledAt\n    trackingSince\n    latestVersion\n    latestDate\n    notice {\n      message\n      linkText\n      coordinate\n      href\n    }\n    summaries {\n      rolling {\n        year\n        month\n        windowDays\n        summary\n        releaseCount\n        generatedAt\n      }\n      monthly {\n        year\n        month\n        windowDays\n        summary\n        releaseCount\n        generatedAt\n      }\n    }\n    org {\n      id\n      slug\n      name\n    }\n    releases(limit: $releaseLimit) {\n      id\n      title\n      version\n      type\n      url\n      publishedAt\n      fetchedAt\n      titleGenerated\n      titleShort\n      content\n      summary\n      media {\n        type\n        url\n        alt\n        r2Url\n      }\n    }\n  }\n}":
    types.SourceDetailDocument,
};

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = graphql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
 */
export function graphql(source: string): unknown;

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: "query CollectionPage($slug: String!, $releaseLimit: Int!) {\n  collection(slug: $slug) {\n    slug\n    name\n    description\n    isFeatured\n    dailySummaryEnabled\n    members {\n      __typename\n      ... on CollectionMemberOrg {\n        slug\n        name\n        domain\n        avatarUrl\n        githubHandle\n        description\n      }\n      ... on CollectionMemberProduct {\n        slug\n        name\n        description\n        org {\n          slug\n          name\n          domain\n          avatarUrl\n          githubHandle\n        }\n      }\n    }\n    releases(limit: $releaseLimit) {\n      nextCursor\n      items {\n        id\n        title\n        version\n        type\n        url\n        publishedAt\n        summary\n        content\n        titleGenerated\n        titleShort\n        prerelease\n        media {\n          type\n          url\n          alt\n          r2Url\n        }\n        source {\n          slug\n          name\n          type\n        }\n        org {\n          slug\n          name\n        }\n        product {\n          slug\n          name\n        }\n        groupSlug\n        groupName\n        coverageCount\n        composition {\n          bugs\n          features\n          enhancements\n        }\n      }\n    }\n    dailySummaries {\n      date\n      title\n      summary\n      takeaways\n      releaseCount\n    }\n  }\n}",
): (typeof documents)["query CollectionPage($slug: String!, $releaseLimit: Int!) {\n  collection(slug: $slug) {\n    slug\n    name\n    description\n    isFeatured\n    dailySummaryEnabled\n    members {\n      __typename\n      ... on CollectionMemberOrg {\n        slug\n        name\n        domain\n        avatarUrl\n        githubHandle\n        description\n      }\n      ... on CollectionMemberProduct {\n        slug\n        name\n        description\n        org {\n          slug\n          name\n          domain\n          avatarUrl\n          githubHandle\n        }\n      }\n    }\n    releases(limit: $releaseLimit) {\n      nextCursor\n      items {\n        id\n        title\n        version\n        type\n        url\n        publishedAt\n        summary\n        content\n        titleGenerated\n        titleShort\n        prerelease\n        media {\n          type\n          url\n          alt\n          r2Url\n        }\n        source {\n          slug\n          name\n          type\n        }\n        org {\n          slug\n          name\n        }\n        product {\n          slug\n          name\n        }\n        groupSlug\n        groupName\n        coverageCount\n        composition {\n          bugs\n          features\n          enhancements\n        }\n      }\n    }\n    dailySummaries {\n      date\n      title\n      summary\n      takeaways\n      releaseCount\n    }\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: "query HomepageAllOrgs($limit: Int!) {\n  orgs(includeEmpty: false, limit: $limit) {\n    items {\n      slug\n      name\n      domain\n      avatarUrl\n      sourceCount\n      releaseCount\n      recentReleaseCount\n      lastActivity\n      topProducts\n      sparkline\n    }\n  }\n}",
): (typeof documents)["query HomepageAllOrgs($limit: Int!) {\n  orgs(includeEmpty: false, limit: $limit) {\n    items {\n      slug\n      name\n      domain\n      avatarUrl\n      sourceCount\n      releaseCount\n      recentReleaseCount\n      lastActivity\n      topProducts\n      sparkline\n    }\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: "query HomepageCollections($featured: Boolean) {\n  collections(featured: $featured) {\n    slug\n    name\n    description\n    memberCount\n    isFeatured\n    previewMembers {\n      __typename\n      ... on CollectionMemberOrg {\n        slug\n        name\n        avatarUrl\n        githubHandle\n      }\n      ... on CollectionMemberProduct {\n        slug\n        name\n        org {\n          slug\n          name\n          avatarUrl\n          githubHandle\n        }\n      }\n    }\n  }\n}",
): (typeof documents)["query HomepageCollections($featured: Boolean) {\n  collections(featured: $featured) {\n    slug\n    name\n    description\n    memberCount\n    isFeatured\n    previewMembers {\n      __typename\n      ... on CollectionMemberOrg {\n        slug\n        name\n        avatarUrl\n        githubHandle\n      }\n      ... on CollectionMemberProduct {\n        slug\n        name\n        org {\n          slug\n          name\n          avatarUrl\n          githubHandle\n        }\n      }\n    }\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: "query HomepageOrgsStats($featuredLimit: Int!) {\n  stats {\n    orgs\n    sources\n    releases\n  }\n  featuredOrgs: orgs(featured: true, limit: $featuredLimit) {\n    items {\n      slug\n      name\n      domain\n      avatarUrl\n      sourceCount\n      releaseCount\n      recentReleaseCount\n      lastActivity\n      topProducts\n      sparkline\n    }\n  }\n}",
): (typeof documents)["query HomepageOrgsStats($featuredLimit: Int!) {\n  stats {\n    orgs\n    sources\n    releases\n  }\n  featuredOrgs: orgs(featured: true, limit: $featuredLimit) {\n    items {\n      slug\n      name\n      domain\n      avatarUrl\n      sourceCount\n      releaseCount\n      recentReleaseCount\n      lastActivity\n      topProducts\n      sparkline\n    }\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: "query HomepageTicker($limit: Int!, $exclude: [SourceType!]!) {\n  latestReleases(limit: $limit, excludeSourceTypes: $exclude) {\n    items {\n      id\n      title\n      version\n      publishedAt\n      titleGenerated\n      titleShort\n      source {\n        org {\n          slug\n          name\n          avatarUrl\n        }\n        product {\n          slug\n          name\n        }\n        appStore {\n          platform\n          iconUrl\n        }\n        video {\n          provider\n        }\n      }\n    }\n  }\n}",
): (typeof documents)["query HomepageTicker($limit: Int!, $exclude: [SourceType!]!) {\n  latestReleases(limit: $limit, excludeSourceTypes: $exclude) {\n    items {\n      id\n      title\n      version\n      publishedAt\n      titleGenerated\n      titleShort\n      source {\n        org {\n          slug\n          name\n          avatarUrl\n        }\n        product {\n          slug\n          name\n        }\n        appStore {\n          platform\n          iconUrl\n        }\n        video {\n          provider\n        }\n      }\n    }\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: "query OrgPage($idOrSlug: String!) {\n  org(idOrSlug: $idOrSlug) {\n    id\n    slug\n    name\n    domain\n    description\n    category\n    avatarUrl\n    isHidden\n    autoGenerateContent\n    overviewCadenceDays\n    featured\n    fetchPaused\n    discovery\n    status\n    locations\n    tags\n    aliases\n    notice\n    sourceCount\n    releaseCount\n    releasesLast30Days\n    avgReleasesPerWeek\n    lastFetchedAt\n    lastPolledAt\n    trackingSince\n    accounts {\n      platform\n      handle\n    }\n    products {\n      id\n      slug\n      name\n      url\n      description\n      kind\n      createdAt\n      sourceCount\n      releaseCount\n    }\n    collections {\n      slug\n      name\n      description\n      memberCount\n      isFeatured\n    }\n    sources {\n      id\n      slug\n      name\n      type\n      url\n      fetchPriority\n      lastFetchedAt\n      lastPolledAt\n      medianGapDays\n      discovery\n      createdAt\n      kind\n      isPrimary\n      isHidden\n      changeDetectedAt\n      consecutiveNoChange\n      consecutiveErrors\n      nextFetchAfter\n      lastRetieredAt\n      metadata\n      stars\n      starsFetchedAt\n      releaseCount\n      latestVersion\n      latestDate\n      latestAddedAt\n      appStore {\n        platform\n        iconUrl\n      }\n      video {\n        provider\n      }\n      product {\n        slug\n        name\n      }\n    }\n  }\n}",
): (typeof documents)["query OrgPage($idOrSlug: String!) {\n  org(idOrSlug: $idOrSlug) {\n    id\n    slug\n    name\n    domain\n    description\n    category\n    avatarUrl\n    isHidden\n    autoGenerateContent\n    overviewCadenceDays\n    featured\n    fetchPaused\n    discovery\n    status\n    locations\n    tags\n    aliases\n    notice\n    sourceCount\n    releaseCount\n    releasesLast30Days\n    avgReleasesPerWeek\n    lastFetchedAt\n    lastPolledAt\n    trackingSince\n    accounts {\n      platform\n      handle\n    }\n    products {\n      id\n      slug\n      name\n      url\n      description\n      kind\n      createdAt\n      sourceCount\n      releaseCount\n    }\n    collections {\n      slug\n      name\n      description\n      memberCount\n      isFeatured\n    }\n    sources {\n      id\n      slug\n      name\n      type\n      url\n      fetchPriority\n      lastFetchedAt\n      lastPolledAt\n      medianGapDays\n      discovery\n      createdAt\n      kind\n      isPrimary\n      isHidden\n      changeDetectedAt\n      consecutiveNoChange\n      consecutiveErrors\n      nextFetchAfter\n      lastRetieredAt\n      metadata\n      stars\n      starsFetchedAt\n      releaseCount\n      latestVersion\n      latestDate\n      latestAddedAt\n      appStore {\n        platform\n        iconUrl\n      }\n      video {\n        provider\n      }\n      product {\n        slug\n        name\n      }\n    }\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: "query OrgReleases($orgIdOrSlug: String!, $limit: Int!) {\n  latestReleases(orgIdOrSlug: $orgIdOrSlug, limit: $limit) {\n    nextCursor\n    items {\n      id\n      title\n      version\n      type\n      url\n      publishedAt\n      fetchedAt\n      summary\n      titleGenerated\n      titleShort\n      content\n      prerelease\n      breaking\n      media {\n        type\n        url\n        alt\n        r2Url\n      }\n      source {\n        slug\n        name\n        type\n        appStore {\n          platform\n          iconUrl\n        }\n        video {\n          provider\n        }\n        product {\n          slug\n          name\n        }\n      }\n    }\n  }\n}",
): (typeof documents)["query OrgReleases($orgIdOrSlug: String!, $limit: Int!) {\n  latestReleases(orgIdOrSlug: $orgIdOrSlug, limit: $limit) {\n    nextCursor\n    items {\n      id\n      title\n      version\n      type\n      url\n      publishedAt\n      fetchedAt\n      summary\n      titleGenerated\n      titleShort\n      content\n      prerelease\n      breaking\n      media {\n        type\n        url\n        alt\n        r2Url\n      }\n      source {\n        slug\n        name\n        type\n        appStore {\n          platform\n          iconUrl\n        }\n        video {\n          provider\n        }\n        product {\n          slug\n          name\n        }\n      }\n    }\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: "query ProductPage($id: String!, $releaseLimit: Int!) {\n  product(id: $id) {\n    id\n    slug\n    name\n    url\n    description\n    category\n    tags\n    notice {\n      message\n      linkText\n      coordinate\n      href\n    }\n    sources {\n      id\n      slug\n      name\n      type\n      url\n      metadata\n      isHidden\n    }\n    collections {\n      slug\n      name\n      description\n      memberCount\n      isFeatured\n    }\n  }\n  latestReleases(productId: $id, limit: $releaseLimit) {\n    nextCursor\n    items {\n      id\n      title\n      version\n      type\n      url\n      publishedAt\n      fetchedAt\n      summary\n      titleGenerated\n      titleShort\n      content\n      prerelease\n      breaking\n      media {\n        type\n        url\n        alt\n        r2Url\n      }\n      source {\n        slug\n        name\n        type\n        appStore {\n          platform\n          iconUrl\n        }\n        video {\n          provider\n        }\n        product {\n          slug\n          name\n        }\n      }\n    }\n  }\n}",
): (typeof documents)["query ProductPage($id: String!, $releaseLimit: Int!) {\n  product(id: $id) {\n    id\n    slug\n    name\n    url\n    description\n    category\n    tags\n    notice {\n      message\n      linkText\n      coordinate\n      href\n    }\n    sources {\n      id\n      slug\n      name\n      type\n      url\n      metadata\n      isHidden\n    }\n    collections {\n      slug\n      name\n      description\n      memberCount\n      isFeatured\n    }\n  }\n  latestReleases(productId: $id, limit: $releaseLimit) {\n    nextCursor\n    items {\n      id\n      title\n      version\n      type\n      url\n      publishedAt\n      fetchedAt\n      summary\n      titleGenerated\n      titleShort\n      content\n      prerelease\n      breaking\n      media {\n        type\n        url\n        alt\n        r2Url\n      }\n      source {\n        slug\n        name\n        type\n        appStore {\n          platform\n          iconUrl\n        }\n        video {\n          provider\n        }\n        product {\n          slug\n          name\n        }\n      }\n    }\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: "query ReleaseDetail($idOrUrl: String!) {\n  release(idOrUrl: $idOrUrl) {\n    id\n    title\n    version\n    type\n    url\n    publishedAt\n    fetchedAt\n    summary\n    titleGenerated\n    titleShort\n    content\n    migrationNotes\n    composition {\n      bugs\n      features\n      enhancements\n    }\n    media {\n      type\n      url\n      alt\n      r2Url\n    }\n    source {\n      slug\n      name\n      type\n      isHidden\n      org {\n        slug\n        name\n        avatarUrl\n        isHidden\n        discovery\n      }\n      product {\n        slug\n        name\n      }\n      appStore {\n        platform\n        iconUrl\n      }\n      video {\n        provider\n      }\n    }\n  }\n}",
): (typeof documents)["query ReleaseDetail($idOrUrl: String!) {\n  release(idOrUrl: $idOrUrl) {\n    id\n    title\n    version\n    type\n    url\n    publishedAt\n    fetchedAt\n    summary\n    titleGenerated\n    titleShort\n    content\n    migrationNotes\n    composition {\n      bugs\n      features\n      enhancements\n    }\n    media {\n      type\n      url\n      alt\n      r2Url\n    }\n    source {\n      slug\n      name\n      type\n      isHidden\n      org {\n        slug\n        name\n        avatarUrl\n        isHidden\n        discovery\n      }\n      product {\n        slug\n        name\n      }\n      appStore {\n        platform\n        iconUrl\n      }\n      video {\n        provider\n      }\n    }\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: "query SourceDetail($id: String!, $releaseLimit: Int!) {\n  source(id: $id) {\n    id\n    slug\n    name\n    type\n    url\n    productId\n    isHidden\n    discovery\n    metadata\n    changelogUrl\n    hasChangelogFile\n    lastFetchedAt\n    lastPolledAt\n    trackingSince\n    latestVersion\n    latestDate\n    notice {\n      message\n      linkText\n      coordinate\n      href\n    }\n    summaries {\n      rolling {\n        year\n        month\n        windowDays\n        summary\n        releaseCount\n        generatedAt\n      }\n      monthly {\n        year\n        month\n        windowDays\n        summary\n        releaseCount\n        generatedAt\n      }\n    }\n    org {\n      id\n      slug\n      name\n    }\n    releases(limit: $releaseLimit) {\n      id\n      title\n      version\n      type\n      url\n      publishedAt\n      fetchedAt\n      titleGenerated\n      titleShort\n      content\n      summary\n      media {\n        type\n        url\n        alt\n        r2Url\n      }\n    }\n  }\n}",
): (typeof documents)["query SourceDetail($id: String!, $releaseLimit: Int!) {\n  source(id: $id) {\n    id\n    slug\n    name\n    type\n    url\n    productId\n    isHidden\n    discovery\n    metadata\n    changelogUrl\n    hasChangelogFile\n    lastFetchedAt\n    lastPolledAt\n    trackingSince\n    latestVersion\n    latestDate\n    notice {\n      message\n      linkText\n      coordinate\n      href\n    }\n    summaries {\n      rolling {\n        year\n        month\n        windowDays\n        summary\n        releaseCount\n        generatedAt\n      }\n      monthly {\n        year\n        month\n        windowDays\n        summary\n        releaseCount\n        generatedAt\n      }\n    }\n    org {\n      id\n      slug\n      name\n    }\n    releases(limit: $releaseLimit) {\n      id\n      title\n      version\n      type\n      url\n      publishedAt\n      fetchedAt\n      titleGenerated\n      titleShort\n      content\n      summary\n      media {\n        type\n        url\n        alt\n        r2Url\n      }\n    }\n  }\n}"];

export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> =
  TDocumentNode extends DocumentNode<infer TType, any> ? TType : never;
