import type { Metadata } from "next";
import { enableOnDemandIsr } from "@/lib/static-params";
import { ChangelogPage, changelogMetadata } from "./_lib/changelog-page";

// On-demand ISR: the plain changelog URL renders once and is served from cache
// (regenerated by the API's revalidate ping; 24h backstop). `?path=` /
// `?offset=` deep links are rewritten by the routing proxy to `changelog/deep`,
// so this route reads no query string and stays cacheable (#2461).
// Keep in sync with DEFAULT_REVALIDATE_SECONDS (src/lib/isr.ts).
export const revalidate = 86400;
export const generateStaticParams = enableOnDemandIsr;

export async function generateMetadata({
  params,
}: {
  params: Promise<{ orgSlug: string; slug: string }>;
}): Promise<Metadata> {
  const { orgSlug, slug } = await params;
  return changelogMetadata(orgSlug, slug);
}

export default async function SourceChangelogPage({
  params,
}: {
  params: Promise<{ orgSlug: string; slug: string }>;
}) {
  const { orgSlug, slug } = await params;
  return <ChangelogPage orgSlug={orgSlug} slug={slug} />;
}
