/**
 * Bundle each MCP App UI into a single self-contained HTML string and emit
 * the strings as a `.ts` module the worker imports. Replaces Vite +
 * vite-plugin-singlefile with Bun's native bundler.
 *
 * Per app:
 *   1. `Bun.build` resolves the React entry (`app.tsx`) and its imports into
 *      one ESM bundle targeting the browser.
 *   2. The sibling `styles.css` is read verbatim.
 *   3. JS + CSS get inlined into a minimal HTML shell.
 *   4. The HTML is written into `src/ui-bundles.ts` as a string export so
 *      Wrangler can pick it up at deploy time without a filesystem at runtime.
 *
 * Adding a new app: drop a folder under `ui/` containing `app.tsx` and
 * `styles.css`, add an entry to APPS below, run `bun run mcp:ui:build`.
 */
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT_FILE = resolve(HERE, "..", "src", "ui-bundles.ts");

const isDev = process.env.NODE_ENV === "development";

interface App {
  /** Identifier used to key the generated string export. */
  name: string;
  /** Directory under `ui/` containing `app.tsx` and `styles.css`. */
  dir: string;
  /** `<title>` for the rendered HTML. Shown by the host before the JS boots. */
  title: string;
}

const APPS: App[] = [
  {
    name: "releaseFeed",
    dir: "release-feed",
    title: "Releases — Feed",
  },
];

function htmlShell(opts: { title: string; css: string; js: string }): string {
  // <meta name="color-scheme"> lets the host pick up our light/dark intent
  // before any host-context handshake happens.
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="color-scheme" content="light dark">
<title>${escapeHtml(opts.title)}</title>
<style>${opts.css}</style>
</head>
<body>
<div id="root"></div>
<script type="module">${opts.js}</script>
</body>
</html>`;
}

function escapeHtml(s: string): string {
  return s
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;");
}

async function buildApp(app: App): Promise<{ name: string; html: string }> {
  const entry = join(HERE, app.dir, "app.tsx");
  const cssPath = join(HERE, app.dir, "styles.css");

  const result = await Bun.build({
    entrypoints: [entry],
    target: "browser",
    minify: !isDev,
    sourcemap: isDev ? "inline" : "none",
    format: "esm",
    external: [],
  });

  if (!result.success) {
    const errors = result.logs.map((l) => l.message).join("\n");
    throw new Error(`Build failed for ${app.name}:\n${errors}`);
  }

  if (result.outputs.length === 0) {
    throw new Error(`Build for ${app.name} produced no output.`);
  }

  const js = await result.outputs[0]!.text();
  const css = await readFile(cssPath, "utf8");

  // React's compiled error strings contain literal `</script>` substrings.
  // Inlined as-is in `<script>…</script>`, the HTML parser sees that as a
  // tag close and renders the JS tail as visible body text. Escaping `</`
  // → `<\/` is JS-semantics-preserving (backslash inside non-special
  // sequences is ignored in strings and regexes) and stops HTML parsing.
  // Same hazard for `</style>` inside CSS, though our hand-written CSS
  // shouldn't trip it — escape both anyway for defense.
  const safeJs = js.replaceAll("</", "<\\/");
  const safeCss = css.replaceAll("</", "<\\/");

  return {
    name: app.name,
    html: htmlShell({ title: app.title, css: safeCss, js: safeJs }),
  };
}

// String literals with backticks: escape ` and ${ so an inlined React
// expression like `${count}` in the JS doesn't break the host file.
function escapeTemplate(s: string): string {
  return s.replaceAll("\\", "\\\\").replaceAll("`", "\\`").replaceAll("${", "\\${");
}

async function emit(builds: { name: string; html: string }[]): Promise<void> {
  const header = `// AUTO-GENERATED by workers/mcp/ui/build.ts — do not edit by hand.
// Regenerate with \`bun run mcp:ui:build\` from the repo root.

`;

  const body = builds
    .map((b) => `export const ${b.name}Html = \`${escapeTemplate(b.html)}\`;\n`)
    .join("\n");

  await mkdir(dirname(OUT_FILE), { recursive: true });
  await writeFile(OUT_FILE, header + body, "utf8");
}

async function main() {
  const builds = await Promise.all(APPS.map(buildApp));
  await emit(builds);
  const sizes = builds.map((b) => `${b.name}=${(b.html.length / 1024).toFixed(1)}kB`).join(" ");
  console.log(`Built ${builds.length} app(s): ${sizes}`);
  console.log(`Wrote ${OUT_FILE}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
