-- AI-scored newsworthiness (1-5, nullable) on releases, generated by the
-- same Haiku release-content pass as summary/title_generated/title_short.
-- Additive, fail-open: no default — existing rows and any unclassified
-- release stay NULL until the model scores it.
ALTER TABLE releases ADD COLUMN importance INTEGER;
