-- #699 Phase D: standalone index on sources.slug for slug-only lookups.
--
-- Phase C of #690 dropped the global UNIQUE(slug) constraint that had been
-- doubling as an index, leaving only the composite idx_sources_org_slug
-- (org_id, slug). SQLite can't service `WHERE slug = ?` from the composite
-- without an org_id predicate, so every slug-only lookup full-scans sources.
--
-- The hot offender is the usage_log dual-write resolver in
-- workers/api/src/routes/usage-log.ts (every extract operation does a
-- slug → id lookup), but slug-only queries also live in workers/mcp/src/tools.ts,
-- workers/api/src/routes/workflows.ts, and workers/api/src/utils.ts.
-- The 699 backfill SQL (scripts/migrations/699-backfill-source-id.sql) also
-- benefits — its correlated subquery does one slug lookup per usage_log row.
--
-- Apply BEFORE running the backfill so the subquery doesn't full-scan.
CREATE INDEX IF NOT EXISTS idx_sources_slug ON sources(slug);
