-- #756: composite index for (published_at DESC, id DESC) cursor walks.
--
-- The GraphQL `latestReleases` resolver and REST `/v1/orgs/:slug/releases`
-- both order by `(published_at DESC, id DESC)` and tiebreak the cursor on
-- `id` when `published_at` is equal. The existing `idx_releases_published`
-- only covers `published_at` alone, so ties on `published_at` (common —
-- batch ingest stamps dozens of rows with a single poll-cycle timestamp)
-- force a filesort over the tied range.
--
-- DESC ordering is explicit because SQLite can walk a DESC index forward
-- to satisfy `ORDER BY ... DESC` without a reverse-scan plan, which keeps
-- the cursor predicate (`(published_at, id) < (?, ?)`) on the optimizer's
-- happy path. (An ASC index would also work — SQLite reverses scans
-- transparently — but matching the ORDER BY direction is the conservative
-- pick and avoids relying on the reverse-scan optimizer staying smart.)
--
-- The single-column `idx_releases_published` is intentionally NOT dropped
-- here. Many REST endpoints filter or order on `published_at` alone, and
-- although the composite's leading column can serve those queries, the
-- single-column index is physically smaller and may be the optimizer's
-- pick for narrow scans. Drop is a follow-up if/when EXPLAIN shows the
-- single-column form is unused.
CREATE INDEX idx_releases_published_id ON releases (published_at DESC, id DESC);
