-- #699 Phase D step 5: drop usage_log.source_slug now that source_id has been
-- backfilled (scripts/migrations/699-backfill-source-id.sql) and dual-write
-- has been live since #704.
--
-- usage_log is a leaf table (no child FK references), so a plain
-- ALTER TABLE DROP COLUMN works under `wrangler d1 migrations apply` — no
-- table-rebuild dance required. SQLite supports DROP COLUMN since 3.35; D1's
-- runtime is well past that.
--
-- The column is not indexed (idx_sources_slug lives on `sources`, not
-- `usage_log`) and not referenced by any view, so DROP COLUMN is safe.
--
-- After this lands, rows whose source has since been deleted lose their
-- per-source attribution (source_id becomes NULL via the existing
-- ON DELETE SET NULL FK), but they still contribute to the totals and the
-- by-operation / by-model rollups in /v1/admin/logs/usage/stats.
ALTER TABLE usage_log DROP COLUMN source_slug;
