import { Hono } from "hono";
import { describeRoute, resolver } from "hono-openapi";
import { eq, and, sql } from "drizzle-orm";
import { createDb } from "../db.js";
import {
  knowledgePages,
  organizations,
  sourcesActive,
  productsActive,
} from "@buildinternet/releases-core/schema";
import { generatePlaybookHeader } from "@releases/ai-internal/playbook";
import { authMiddleware } from "../middleware/auth.js";
import { newKnowledgePageId, orgWhere } from "../utils.js";
import { validateJson } from "../lib/validate.js";
import {
  PlaybookResponseSchema,
  UpdatePlaybookNotesBodySchema,
  UpdatePlaybookNotesResponseSchema,
  ErrorResponseSchema,
} from "@buildinternet/releases-api-types";
import type { Env } from "../index.js";

const app = new Hono<Env>();

// Playbook content is internal — force admin auth even on GET.
app.get(
  "/orgs/:slug/playbook",
  describeRoute({
    tags: ["Playbook"],
    summary: "Get org playbook",
    description:
      'Returns the org\'s playbook knowledge page (scope `"playbook"`), or `null` when no playbook has been created yet. The playbook `content` field holds a deterministic markdown header generated by `generatePlaybookHeader()`. Playbook content is internal — admin Bearer auth is required even for reads.',
    security: [{ bearerAuth: [] }],
    responses: {
      200: {
        description: "Org playbook page, or null when none exists",
        content: { "application/json": { schema: resolver(PlaybookResponseSchema) } },
      },
    },
  }),
  authMiddleware,
  async (c) => {
    const db = createDb(c.env.DB);
    const slug = c.req.param("slug");

    const [org] = await db
      .select({ id: organizations.id })
      .from(organizations)
      .where(orgWhere(slug));
    if (!org) return c.json(null);

    const [row] = await db
      .select()
      .from(knowledgePages)
      .where(and(eq(knowledgePages.scope, "playbook"), eq(knowledgePages.orgId, org.id)));

    if (!row) return c.json(null);

    return c.json(row);
  },
);

app.patch(
  "/orgs/:slug/playbook/notes",
  describeRoute({
    tags: ["Playbook"],
    summary: "Update playbook notes",
    description:
      "Updates the `notes` field on the org's playbook knowledge page. Accepts a JSON body with a `notes` string; an empty string is stored as `null`. If no playbook row exists yet, one is bootstrapped with a generated header before the notes are applied. Requires Bearer auth inherited from `publicReadAuthMiddleware`'s non-SAFE_METHODS branch.",
    security: [{ bearerAuth: [] }],
    responses: {
      200: {
        description: "Notes updated",
        content: { "application/json": { schema: resolver(UpdatePlaybookNotesResponseSchema) } },
      },
      400: {
        description: "Missing or invalid `notes` field, or malformed JSON body",
        content: { "application/json": { schema: resolver(ErrorResponseSchema) } },
      },
      404: {
        description: "Org not found",
        content: { "application/json": { schema: resolver(ErrorResponseSchema) } },
      },
    },
  }),
  validateJson(UpdatePlaybookNotesBodySchema),
  async (c) => {
    const db = createDb(c.env.DB);
    const slug = c.req.param("slug");
    const body = c.req.valid("json");

    const [org] = await db
      .select({
        id: organizations.id,
        name: organizations.name,
        slug: organizations.slug,
        domain: organizations.domain,
      })
      .from(organizations)
      .where(orgWhere(slug));
    if (!org) return c.json({ error: "Organization not found" }, 404);

    const [existing] = await db
      .select()
      .from(knowledgePages)
      .where(and(eq(knowledgePages.scope, "playbook"), eq(knowledgePages.orgId, org.id)));

    const now = new Date().toISOString();
    const notes = body.notes.trim() || null;

    if (existing) {
      await db.run(sql`UPDATE knowledge_pages SET notes = ${notes}, updated_at = ${now}
        WHERE scope = 'playbook' AND org_id = ${org.id}`);
    } else {
      const orgSources = await db
        .select()
        .from(sourcesActive)
        .where(eq(sourcesActive.orgId, org.id));
      const orgProducts = await db
        .select({
          id: productsActive.id,
          name: productsActive.name,
          slug: productsActive.slug,
          description: productsActive.description,
        })
        .from(productsActive)
        .where(eq(productsActive.orgId, org.id));

      const header = generatePlaybookHeader({
        orgName: org.name,
        orgSlug: org.slug,
        domain: org.domain,
        sources: orgSources,
        products: orgProducts.map((p) => ({
          id: p.id,
          name: p.name,
          slug: p.slug,
          description: p.description,
        })),
      });

      const id = newKnowledgePageId();
      await db.run(sql`INSERT INTO knowledge_pages (id, scope, org_id, product_id, content, notes, release_count, generated_at, updated_at)
        VALUES (${id}, 'playbook', ${org.id}, NULL, ${header}, ${notes}, ${orgSources.length}, ${now}, ${now})`);
    }

    return c.json({ ok: true, notes });
  },
);

export default app;
